version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - echo Entered the install phase...
      - npm install -g npm@latest
      - npm ci

  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo Build started on `date`

  build:
    commands:
      - echo Entered the build phase...
      - npm run build

  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

artifacts:
  files:
    - "**/*"
  base-directory: .next
  discard-paths: no
