

export const posts: any[] = [
    {
        id: 1,
        title: 'Component-driven design today',
        description: 'Explore how component-driven design is transforming modern frontend development workflows and improving scalability.',
        image: 'https://design.intentui.com/images/blocks/blog/blog-min.jpg',
        tags: ['frontend', 'design', 'architecture'],
        authors: [{ name: 'Sabrina Lang', avatarUrl: 'https://i.pravatar.cc/150?u=u101' }],
        date: '10 Jul',
    },
    {
        id: 2,
        title: 'Server actions in Laravel 12',
        description: 'An in-depth look at how Server Actions in Laravel 11 simplify request handling and improve developer productivity.',
        image: 'https://design.intentui.com/images/blocks/blog/blog-min.jpg',
        tags: ['laravel', 'php'],
        authors: [{ name: 'Jason', avatarUrl: 'https://i.pravatar.cc/150?u=u205' }],
        date: '14 Jul',
    },
    {
        id: 3,
        title: 'Scaling react app performance',
        description: 'A guide to identifying and fixing performance bottlenecks in large-scale React applications with real-world strategies.',
        image: 'https://design.intentui.com/images/blocks/blog/blog-min.jpg',
        tags: ['performance', 'optimization'],
        authors: [
            { name: 'Author One', avatarUrl: 'https://i.pravatar.cc/150?u=u333' },
            { name: 'Author Two', avatarUrl: 'https://i.pravatar.cc/150?u=u444' },
            { name: 'Author Three', avatarUrl: 'https://i.pravatar.cc/150?u=u555' },
        ],
        date: '20 Jul',
    },
    {
        id: 4,
        title: 'React state without libraries',
        description: 'Learn how to manage complex state in React without relying on external libraries like Redux or Zustand.',
        image: 'https://design.intentui.com/images/blocks/blog/blog-min.jpg',
        tags: ['react', 'state', 'javascript'],
        authors: [{ name: 'Jason', avatarUrl: 'https://i.pravatar.cc/150?u=u205' }],
        date: '03 Jul',
    },
    {
        id: 5,
        title: 'Modern CSS layout tricks',
        description: 'CSS Grid, Flexbox, and container queries: explore the modern layout tools that simplify responsive design.',
        image: 'https://design.intentui.com/images/blocks/blog/blog-min.jpg',
        tags: ['css', 'responsive', 'webdev'],
        authors: [{ name: 'Sabrina Lang', avatarUrl: 'https://i.pravatar.cc/150?u=u101' }],
        date: '08 Jul',
    },
    {
        id: 6,
        title: 'Dashboards with Tailwind UI',
        description: 'A practical walkthrough for building beautiful and scalable SaaS dashboards using Tailwind CSS and React.',
        image: 'https://design.intentui.com/images/blocks/blog/blog-min.jpg',
        tags: ['tailwind', 'react', 'dashboard'],
        authors: [{ name: 'Hana Kobayashi', avatarUrl: 'https://i.pravatar.cc/150?u=u888' }],
        date: '17 Jul',
    },
    {
        id: 7,
        title: 'Why typescript still matters',
        description: 'Explore the benefits of TypeScript in preventing bugs, improving tooling, and scaling large codebases.',
        image: 'https://design.intentui.com/images/blocks/blog/blog-min.jpg',
        tags: ['typescript', 'javascript', 'tooling'],
        authors: [{ name: 'Leo Ward', avatarUrl: 'https://i.pravatar.cc/150?u=u999' }],
        date: '01 Jul',
    },
    {
        id: 8,
        title: 'Boost SEO with Lighthouse tips',
        description: 'A deep dive into improving Lighthouse performance, accessibility, and SEO scores for modern websites.',
        image: 'https://design.intentui.com/images/blocks/blog/blog-min.jpg',
        tags: ['seo', 'performance', 'lighthouse'],
        authors: [{ name: 'Malik Adam', avatarUrl: 'https://i.pravatar.cc/150?u=u111' }],
        date: '06 Jul',
    },
    {
        id: 9,
        title: 'Deploying fullstack on Vercel',
        description: 'Learn how to deploy fullstack applications using Vercel’s edge functions, serverless features, and seamless CI/CD.',
        image: 'https://design.intentui.com/images/blocks/blog/blog-min.jpg',
        tags: ['vercel', 'deployment', 'fullstack'],
        authors: [
            { name: 'Jason', avatarUrl: 'https://i.pravatar.cc/150?u=u205' },
            { name: 'Hana Kobayashi', avatarUrl: 'https://i.pravatar.cc/150?u=u888' },
            { name: 'Author One', avatarUrl: 'https://i.pravatar.cc/150?u=u333' },
        ],
        date: '09 Jul',
    },
];